"""Watermark audit: run a detector over REAL generated audio, not over documentation.

WHY THIS EXISTS AS CODE. Every model card in this space makes watermarking claims and at
least one of them is false in an expensive direction. Microsoft's VibeVoice card states, in
its own words, that the release "embedded an audible disclaimer ... automatically into
every synthesized audio file" and "added an imperceptible watermark". Neither is in the
shipped code -- a source grep across microsoft/VibeVoice, the community fork and both
ComfyUI wrappers returns zero watermarking call sites. Meanwhile Chatterbox, whose card
says comparatively little about it, applies Resemble's PerTh watermark unconditionally in
the default generate() path of all four of its model classes.

So: cards are not evidence, and neither is a grep on its own -- a grep proves the wrapper
is clean but cannot prove the weights are. Only listening to and measuring the output can.
This script does both halves:

  detect   run the open PerTh detector over a clip and report the score
  scan     look for a spoken disclaimer at the head/tail of a clip, which is what a
           trained-in disclosure would look like if one existed

WHAT A POSITIVE MEANS COMMERCIALLY. The PerTh detector is MIT-licensed and needs no key
(`pip install resemble-perth`). Anybody -- a client, a platform, a competitor -- can run it
over a delivered ad and get a yes/no. That is the actual exposure: not that a watermark
exists, but that detecting it is free and unilateral.

USAGE
    python watermark_audit.py detect clip.wav [clip2.wav ...]
    python watermark_audit.py scan   clip.wav          # head/tail energy + transcript hint
    python watermark_audit.py selftest                 # prove the detector works at all

The selftest is not optional ceremony. A detector that silently returns 0.0 for everything
would clear every model in the stack and look like good news, so it is checked against a
clip we KNOW is watermarked before any verdict is trusted.
"""

import os
import sys

THRESHOLD = 0.5  # PerTh returns a 0.0-1.0 confidence; Resemble's own examples treat >0.5 as present


def _load(path):
    import librosa

    wav, sr = librosa.load(path, sr=None, mono=True)
    return wav, sr


def detect(paths):
    """Report a PerTh watermark score per file. Non-zero means Resemble-watermarked."""
    try:
        import perth
    except ImportError:
        sys.exit(
            "resemble-perth is not installed. `pip install resemble-perth`.\n"
            "It is a hard dependency of chatterbox-tts, so it is already present in the "
            "../tts worker image -- run this there, or install it here."
        )

    wm = perth.PerthImplicitWatermarker()
    worst = 0.0
    for p in paths:
        wav, sr = _load(p)
        score = float(wm.get_watermark(wav, sample_rate=sr))
        worst = max(worst, score)
        verdict = "WATERMARKED" if score > THRESHOLD else "clean"
        print(f"{score:6.3f}  {verdict:<12}  {os.path.basename(p)}  ({len(wav)/sr:.1f}s @ {sr}Hz)")
    return worst


def scan(path):
    """Look for a trained-in spoken disclaimer.

    A disclosure baked into the weights rather than the wrapper would show up as speech at
    the very start or very end that is not in the input script. There is no way to detect
    that from the waveform alone, so this prints the head and tail as separate clips and
    tells the operator to listen. Cheap, and the only honest way to answer the question.
    """
    import soundfile as sf

    wav, sr = _load(path)
    dur = len(wav) / sr
    head_n, tail_n = int(min(6.0, dur) * sr), int(min(6.0, dur) * sr)
    base = os.path.splitext(path)[0]
    sf.write(f"{base}.head.wav", wav[:head_n], sr)
    sf.write(f"{base}.tail.wav", wav[-tail_n:], sr)
    print(f"{path}: {dur:.1f}s")
    print(f"  wrote {base}.head.wav and {base}.tail.wav")
    print("  LISTEN to both. A trained-in disclosure ('this segment was generated by AI',")
    print("  or an equivalent in the output language) would sit in one of them and would")
    print("  not appear in your input script. Transcribe them with the ../stt worker if")
    print("  you would rather read than listen -- faster-whisper large-v3 will catch it.")


def selftest():
    """Prove the detector actually detects, using a clip we watermark ourselves.

    Without this, a detector that returns 0.0 unconditionally would silently clear the
    whole stack. Applying a known watermark and failing to find it is the one result that
    invalidates every other line this script prints.
    """
    try:
        import numpy as np
        import perth
    except ImportError:
        sys.exit("need resemble-perth and numpy for the selftest")

    sr = 24000
    rng = np.random.default_rng(0)
    # Speech-ish rather than pure noise: PerTh is tuned for voice, and a tone or white
    # noise is not a fair test of a detector built for speech spectra.
    t = np.arange(sr * 3) / sr
    clean = (0.3 * np.sin(2 * np.pi * 140 * t) * (1 + 0.5 * np.sin(2 * np.pi * 3 * t))
             + 0.02 * rng.standard_normal(len(t))).astype("float32")

    wm = perth.PerthImplicitWatermarker()
    marked = wm.apply_watermark(clean, sample_rate=sr)

    s_clean = float(wm.get_watermark(clean, sample_rate=sr))
    s_marked = float(wm.get_watermark(marked, sample_rate=sr))
    print(f"unmarked control : {s_clean:.3f}")
    print(f"marked control   : {s_marked:.3f}")

    if not s_marked > THRESHOLD:
        sys.exit(
            "SELFTEST FAILED: the detector did not find a watermark it had just applied.\n"
            "Every 'clean' verdict from this script is therefore meaningless. Fix the "
            "detector before trusting any audit result."
        )
    if s_clean > THRESHOLD:
        sys.exit(
            "SELFTEST FAILED: the detector flagged an unmarked control.\n"
            "False positives make every 'WATERMARKED' verdict meaningless too."
        )
    print("selftest OK -- detector separates marked from unmarked, verdicts are trustworthy")


if __name__ == "__main__":
    if len(sys.argv) < 2:
        sys.exit(__doc__)
    cmd = sys.argv[1]
    if cmd == "selftest":
        selftest()
    elif cmd == "detect":
        if not sys.argv[2:]:
            sys.exit("usage: watermark_audit.py detect <wav> [wav ...]")
        # Exit non-zero when anything is watermarked so this can gate a release pipeline
        # rather than only informing a human who may not be reading.
        sys.exit(1 if detect(sys.argv[2:]) > THRESHOLD else 0)
    elif cmd == "scan":
        if not sys.argv[2:]:
            sys.exit("usage: watermark_audit.py scan <wav>")
        scan(sys.argv[2])
    else:
        sys.exit(__doc__)
